"""introducing comments

Revision ID: 36b96eb64afd
Revises: 334f39e96eba
Create Date: 2019-08-12 17:15:36.358572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b96eb64afd'
down_revision = '334f39e96eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'post_id')
    # ### end Alembic commands ###
